[package]
name = "happycache"
version = "0.1.0"
authors = ["Josh Snyder <josh@code406.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.26"
libc = "0.2.147"
